/*!
 * CartMan v0.2.14
 * Vladimir Ivanin
 * 2018
 */
(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
var getDataAttrName=require("./help").getDataAttrName,system=require("../variables").system;function deleteItems(e,t){var s=getDataAttrName(system.selectors.item_delete),r=getDataAttrName(system.selectors.item);if(!$(s).length)return!1;var a=[];$.each(Cart.order.order_lines,function(e,t){a.push(getDataAttrName(system.selectors.item,t.id))});var m=$(r).not(a.join(","));m.addClass(system.classes.removed),e.hideCartItems&&m.slideUp(300,function(){$(this).remove()})}module.exports=deleteItems;
},{"../variables":9,"./help":3}],2:[function(require,module,exports){
var getDataAttrName=require("./help").getDataAttrName,system=require("../variables").system;function updateDiscounts(t){var e=getDataAttrName(system.selectors.discounts);if(!($(e).length&&t))return!1;$.ajax({url:"/cart_items",dataType:"html"}).done(function(t){var a=$(t).find(e).html();$(e).html(a)})}module.exports=updateDiscounts;
},{"../variables":9,"./help":3}],3:[function(require,module,exports){
function getDataAttrName(e,t){return"[data-"+(t?e+'="'+t+'"':e)+"]"}var declinationText=function(e,t){var a=["товар","товара","товаров"];t&&(a=t);return a[e%100>4&&e%100<20?2:[2,0,1,1,1,2][e%10<5?e%10:5]]};function patchNumber(e){var t,a="string"==typeof e;if(!("number"==typeof e)&&!a)return 0;return a&&(e=(e=(e=e.replace(/\s/g,"")).replace(/,/g,".")).replace(/px/g,""),e=isNaN(+e)?1:+e),Number((t=e,Number(t)===t&&t%1!=0?e.toFixed(2):e))}function getTemplate(e,t){return e&&"string"==typeof e||(e=""),$.each(t,function(t,a){e=e.replace(a.reg,a.data)}),e}module.exports={getDataAttrName:getDataAttrName,getTemplate:getTemplate,declinationText:declinationText,patchNumber:patchNumber};
},{}],4:[function(require,module,exports){
var defaults=require("../variables").defaults,init=require("./init"),CartMan=function(n){this.state={cart_is_init:!1},this.options=$.extend(!0,{},defaults,n),this.init=init,EventBus?this.init():console.warn("Не подключен common.js")};CartMan.getInstance=function(n){return null==this.instance?this.instance=new CartMan(n):console.warn('CartMan уже объявлен, оставьте один "new CartMan"'),this.instance},module.exports=function(n){return CartMan.getInstance(n)};
},{"../variables":9,"./init":5}],5:[function(require,module,exports){
var updateClasses=require("./updateClasses"),updateDiscounts=require("./discounts"),deleteItems=require("./deleteItems"),updateData=require("./updateData");function init(){var e=this,t=e.options;EventBus.subscribe("delete_items:insales:cart",function(e){deleteItems(t,e),t.deleteItems(e)}),EventBus.subscribe("update_items:insales:cart",function(s){updateData(t,s),updateDiscounts(e.state.cart_is_init),updateClasses(s),t.updateItems(s),e.state.cart_is_init=!0})}module.exports=init;
},{"./deleteItems":1,"./discounts":2,"./updateClasses":6,"./updateData":7}],6:[function(require,module,exports){
var getDataAttrName=require("./help").getDataAttrName,system=require("../variables").system;function updateClasses(e){$.each(system.selectors,function(s,t){var a=$(getDataAttrName(t));0==e.order_lines.length?a.addClass(system.classes.empty):a.removeClass(system.classes.empty)})}module.exports=updateClasses;
},{"../variables":9,"./help":3}],7:[function(require,module,exports){
var getDataAttrName=require("./help").getDataAttrName,declinationText=require("./help").declinationText,patchNumber=require("./help").patchNumber,getTemplate=require("./help").getTemplate,system=require("../variables").system;function updateData(t,e){updateCounts(t,e),updateItemTotal(e.order_lines),updateTotalPrice(e.total_price,e.items_price)}function updateCounts(t,e){var a=$(getDataAttrName(system.selectors.items_count)),o=$(getDataAttrName(system.selectors.positions_count)),s=$(getDataAttrName(system.selectors.items_count_words)),r=$(getDataAttrName(system.selectors.positions_count_words)),m=0==e.order_lines.length?t.counterItemsTextEmpty:t.counterItemsText,n=0==e.order_lines.length?t.counterTemplateEmpty:t.counterTemplate,i=getTemplate(m,[{reg:/%c%/g,data:e.items_count},{reg:/%w%/g,data:declinationText(e.items_count,t.declination)}]),l=getTemplate(n,[{reg:/%c%/g,data:e.items_count}]);a.html(l),s.html(i);var c=0==e.order_lines.length?t.counterPositionTextEmpty:t.counterPositionText,p=0==e.order_lines.length?t.positionsTemplateEmpty:t.positionsTemplate,u=getTemplate(c,[{reg:/%c%/g,data:e.positions_count},{reg:/%w%/g,data:declinationText(e.positions_count,t.declination)}]),d=getTemplate(p,[{reg:/%c%/g,data:e.positions_count}]);o.html(d),r.html(u)}function updateTotalPrice(t,e){var a=$(getDataAttrName(system.selectors.total_price)),o=$(getDataAttrName(system.selectors.items_price));a.html(Shop.money.format(patchNumber(t))),o.html(Shop.money.format(patchNumber(e)))}function updateItemTotal(t){var e=system.item_class;_.forEach(t,function(t){$('[data-item-id="'+t.variant_id+'"]').each(function(a,o){$(o).find(getDataAttrName(system.selectors.item_total_price)).html(Shop.money.format(patchNumber(t.total_price))),$(o).find(getDataAttrName(system.selectors.item_count)).html(t.quantity),1==t.quantity?($(o).addClass(e.one),$(o).removeClass(e.moreOne).removeClass(e.moreNine)):t.quantity>1&&t.quantity<10?($(o).addClass(e.moreOne),$(o).removeClass(e.one).removeClass(e.moreNine)):($(o).addClass(e.moreNine),$(o).removeClass(e.one).removeClass(e.moreOne))})})}module.exports=updateData;
},{"../variables":9,"./help":3}],8:[function(require,module,exports){
window.CartMan=require("CartMan");
},{"CartMan":4}],9:[function(require,module,exports){
var defaults={declination:["товар","товара","товаров"],hideCartItems:!0,counterTemplate:"(%c%)",counterTemplateEmpty:null,positionsTemplate:"(%c%)",positionsTemplateEmpty:null,counterItemsText:"В вашей корзине %c%&nbsp;%w%",counterItemsTextEmpty:"В вашей корзине %c%&nbsp;%w%",counterPositionText:"В вашей корзине %c%&nbsp;%w%",counterPositionTextEmpty:"В вашей корзине %c%&nbsp;%w%",updateItems:function(){},deleteItems:function(){}},system={selectors:{quantity:"cartman-quantity",item:"item-id",item_delete:"item-delete",item_total_price:"cartman-item-total-price",item_count:"cartman-item-count",items_price:"cartman-items-price",total_price:"cartman-total-price",items_count:"cartman-items-count",positions_count:"cartman-positions-count",items_count_words:"cartman-items-text",positions_count_words:"cartman-positions-text",discounts:"cartman-discounts"},classes:{init:"is-cart-init",removed:"is-removed",empty:"is-cart-empty"},item_class:{one:"is-one",moreOne:"more-than-one",moreNine:"more-than-nine"}};module.exports={defaults:defaults,system:system};
},{}]},{},[8]);
